### ISSUE TITLE
Add the "Safari" browser icon

### ISSUE THREAD

**Issue by TimPietrusky** [fontello/fontelico.font#1]
It would be really awesome to include a Safari icon into Fontelico. Why? To be able to create a browser comparison list (or something like that).

**Comment by puzrin** [comment]
Can you provide SVG image?

**Comment by puzrin** [comment]
Closed: no news / no design requests accepted . Feel free to reopen when something changes

**Comment by homotechsual** [comment]
https://www.iconfinder.com/icons/104875/browser_compass_safari_icon <-- Safari SVG icon licensed under CC BY 3.0

**Comment by puzrin** [comment]
1. It's not good in small size.
2. I don't consider fontellico as place for collecting images from internet. Images are accepted, when are good in small size and suggested by author directly.
